apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
  labels:
    cni: kindnet
  name: runtime-sdk-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  controlPlaneEndpoint:
    host: 172.18.0.5
    port: 6443
  topology:
    class: quick-start-runtimesdk
    controlPlane:
      replicas: 1
    version: v1.24.2
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 3